config/routes.rb
Rails.application.routes.draw do
  get 'weapon_images/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  # mount Sidekiq::Web => '/sidekiq'
  resources :weapons
  # get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static_pages#home'
  resources :posts
  resources :users
  get 'us_json', to: "weapons#get_user_versions"
  
  resources :conversations do
    resources :messages
  end
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base

  has_many :weapon_images
  accepts_nested_attributes_for :weapon_images, allow_destroy: true


  monetize :price_kopiykas

  do_not_validate_attachment_file_type :image
  has_attached_file :image,
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("config/dropbox.yml"),
    styles: { medium: "300x300>", thumb: "100x100" },
    default_url: "missing.png",
    dropbox_options: {
      path: proc { |style| "#{style}/#{id}_#{image.original_filename}"}
    }
end

app/controllers/weapons_controller.rb
require 'mechanize'
require 'date'
require 'json'

class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
    # @usd = currency(@weapon.price)
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
    # HardJob.perform_later(12)
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        # HardJob.perform_later(@weapon.id)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

    def get_user_versions
    u = User.find(57)
    render json: { user: u.versions }
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:image, :description, :price)
    end
end

app/helpers/weapons_helper.rb
module WeaponsHelper
  def currency(price)
    agent = Mechanize.new
    page = agent.get("http://finance.i.ua/bank/10/")
    # review_meta = page.search('.local_table')
    # usd =  review_meta.search('tr')[1].search('td big')[0].text
    usd = page.search('big')[0].text
    full = usd.to_f*price.fractional
    Money.new(full, "USD")
  end
end

app/views/weapons/_form.html.slim
= form_for @weapon do |f|
  - if @weapon.errors.any?
    #error_explanation
      h2 = "#{pluralize(@weapon.errors.count, "error")} prohibited this weapon from being saved:"
      ul
        - @weapon.errors.full_messages.each do |message|
          li = message

  .field
    = f.file_field :image
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.number_field :price
  .actions = f.submit

app/views/weapons/edit.html.slim
h1 Editing weapon

== render 'form'

= link_to 'Show', @weapon
'|
= link_to 'Back', weapons_path

app/views/weapons/index.html.slim
h1 Listing weapons

table
  thead
    tr
      th Image
      th Description
      th Price
      th
      th
      th
      th

  tbody
    - @weapons.each do |weapon|
      tr
        td = link_to weapon
          = image_tag(weapon.image(:thumb))
        td = weapon.description
        td = weapon.price.format(:with_currency => true)
        td = currency(weapon.price).format(:with_currency => true)
        td = link_to 'Show', weapon
        td = link_to 'Edit', edit_weapon_path(weapon)
        td = link_to 'Destroy', weapon, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Weapon', new_weapon_path

app/views/weapons/new.html.slim
h1 New weapon

== render 'form'

= link_to 'Back', weapons_path

app/views/weapons/show.html.slim
p#notice = notice


= image_tag @weapon.image.url(:medium)
br
br
p
  = @weapon.description
p
  strong Price:  
  = @weapon.price.format(:with_currency => true)
  span  | 
  = currency(@weapon.price).format(:with_currency => true)
  
= link_to 'Edit', edit_weapon_path(@weapon)
span  | 
= link_to 'Back', weapons_path