config/routes.rb
Rails.application.routes.draw do
  get 'weapon_images/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  # mount Sidekiq::Web => '/sidekiq'
  resources :weapons
  # get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static_pages#home'
  resources :posts
  resources :users
  get 'us_json', to: "weapons#get_user_versions"
  
  resources :conversations do
    resources :messages
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  before_save do
    content.nil? ? 0 : self.short_content = content.slice(0..100)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :content))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for @post, html:{ class: 'form-horizontal' } do |f|
  .field.form-group
    = f.label :title
    br
    = f.text_field :title, class:"form-control"
  .field.form-group
    = f.label :content
    br
    = f.text_area :content, class:"form-control", rows:"5"

  .actions
    = f.submit "Do it!", class:"btn btn-default"
    br

app/views/posts/index.html.slim
.col-md-10.col-md-offset-1
  h1.posts-h1 Amazing blog about your f*king life
  br
  - @posts.each do |post|
    .col-sm-4.posts
      = link_to post_path(post)
        = image_tag "post.png", class: "posts-img"
      h3.text-center
        = link_to "#{post.title}", post_path(post), class: "text-danger"
      .posts-hr
        hr
      .col-sm-12.posts-pdng
        P.text-muted
          = post.short_content
        hr

app/views/posts/new.html.slim
h1 New User
br
.col-sm-6
  = render 'form'
  = link_to 'Back', posts_path

app/views/posts/show.html.slim
.col-sm-12.bgc-wht  
  .col-sm-12.post-img
  .col-md-10.col-md-offset-1
    p.small.text-muted.m-top-30
        = time_ago_in_words(@post.created_at).gsub('about', ' ')
        |  ago by 
        = link_to "#{@post.user.full_name}",user_path(@post.user)
    p.post-title.m-top-30
      = @post.title
    
    p.m-left-10.post-content.m-top-30
      =simple_format(@post.content)
    hr
    .col-sm-8.col-md-offset-2
      .col-sm-2
        = link_to user_path(@post.user) 
          = image_tag @post.user.avatar.url(:thumb)
      .col-sm-10.post-user
        blockquote
          p.post-user-name 
            = @post.user.full_name
          p.text-muted 
            = @post.user.email
    .col-sm-12
      hr
      h3.m-btm-50 Comments: