config/routes.rb
Rails.application.routes.draw do
  get 'weapon_images/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  # mount Sidekiq::Web => '/sidekiq'
  resources :weapons
  # get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static_pages#home'
  resources :posts
  resources :users
  get 'us_json', to: "weapons#get_user_versions"
  
  resources :conversations do
    resources :messages
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head

    title
      | The96Thugs
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'
    / meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  body
    // navbar
    nav.navbar.navbar-inverse
      .contaiЕner
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "THE 96 THUGS", root_url, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to "Home", root_url
            li
              = link_to "Posts", posts_path
            li
              = link_to "Weapons", weapons_path
            - if user_signed_in?
              li
                = link_to "Users", users_path
              li
                = link_to "Add post", new_post_path
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                = link_to "#{current_user.full_name}", user_path(current_user)
              li
                = link_to "Log Out", destroy_user_session_path, method: :delete
            - else
              li
                = link_to "Sign Up", new_user_registration_path
              li
                = link_to "Sign In", new_user_session_path

    .container
      - flash.each do |type, message|
        .alert.fade.in class=(alert_class_for(type))
          = message

      = yield